Student.create!([
  { first_name: "Keena", last_name: "Cummings", email: "keenacummings@example.com", password_digest: "password", phone_number: "657-831-8612", short_bio: "Moon American Apparel +1 stumptown cardigan ethical leggings McSweeney's. High life fanny pack food truck brunch vegan blog gluten-free raw denim. Shoreditch retro keytar you probably haven't heard of them moon. Portland keffiyeh Marfa Austin tofu Rerry Richardson quinoa readymade sustainable. Williamsburg mustache dreamcatcher jean shorts Banksy Wayfarers +1.", linkedin_url: "www.linkedin.com/inkeena.cummings", twitter_handle: nil, personal_website_url: "www.keena.cummings.com", online_resume_url: "www.keena.cummings.com/resume", github_url: "www.github.com/keena.cummings", photo_url: "https://via.placeholder.com/300x300/caac50/5a544d.png?text=" },
  { first_name: "Rossana", last_name: "Russel", email: "rossanarussel@example.com", password_digest: "password", phone_number: "708-775-0745", short_bio: "Squid vegan readymade American Apparel raw denim Williamsburg echo park Austin retro. Vegan mustache readymade mixtape raw denim seitan squid before they sold out. Twee Wes Anderson Cosby Sweater yr farm-to-table Shoreditch.", linkedin_url: "www.linkedin.com/inrossana.russel", twitter_handle: nil, personal_website_url: "www.rossana.russel.com", online_resume_url: "www.rossana.russel.com/resume", github_url: "www.github.com/rossana.russel", photo_url: "https://via.placeholder.com/300x300/c098de/cf827a.png?text=" },
  { first_name: "Somer", last_name: "Beer", email: "somerbeer@example.com", password_digest: "password", phone_number: "799-902-0183", short_bio: "Seitan keytar chambray thundercats jean shorts artisan. Freegan gluten-free irony +1 raw denim Marfa put a bird on it. 8-bit Shoreditch echo park Banksy photo booth. Helvetica aesthetic mlkshk fap tumblr blog echo park yr Wes Anderson.", linkedin_url: "www.linkedin.com/insomer.beer", twitter_handle: nil, personal_website_url: "www.somer.beer.com", online_resume_url: "www.somer.beer.com/resume", github_url: "www.github.com/somer.beer", photo_url: "https://via.placeholder.com/300x300/741853/2d618e.png?text=" },
  { first_name: "Kasandra", last_name: "Haley", email: "kasandrahaley@example.com", password_digest: "password", phone_number: "839-582-3284", short_bio: "Tofu etsy master cleanse retro sustainable keytar brunch banh mi tumblr. Hoodie gluten-free gentrify lo-fi salvia trust fund mustache quinoa letterpress. Irony keffiyeh letterpress messenger bag bicycle rights.", linkedin_url: "www.linkedin.com/inkasandra.haley", twitter_handle: nil, personal_website_url: "www.kasandra.haley.com", online_resume_url: "www.kasandra.haley.com/resume", github_url: "www.github.com/kasandra.haley", photo_url: "https://via.placeholder.com/300x300/86c7f8/c4c8fa.png?text=" },
  { first_name: "Roman", last_name: "Casper", email: "romancasper@example.com", password_digest: "password", phone_number: "561-618-4154", short_bio: "Synth whatever vegan cred Pitchfork viral farm-to-table. Put a bird on it squid keytar 8-bit iPhone mlkshk. Shoreditch squid put a bird on it irony brunch biodiesel 8-bit sartorial. Raw denim PBR twee brunch skateboard readymade Marfa aesthetic.", linkedin_url: "www.linkedin.com/inroman.casper", twitter_handle: nil, personal_website_url: "www.roman.casper.com", online_resume_url: "www.roman.casper.com/resume", github_url: "www.github.com/roman.casper", photo_url: "https://via.placeholder.com/300x300/c8af3b/11e6db.png?text=" },
  { first_name: "Adriane", last_name: "Ward", email: "adrianeward@example.com", password_digest: "password", phone_number: "962-647-7672", short_bio: "Before they sold out organic aesthetic seitan keffiyeh. Single-origin coffee Banksy 8-bit fanny pack food truck +1. Mcsweeney's you probably haven't heard of them iPhone Shoreditch DIY lomo scenester Williamsburg. Austin aesthetic stumptown echo park etsy salvia twee.", linkedin_url: "www.linkedin.com/inadriane.ward", twitter_handle: nil, personal_website_url: "www.adriane.ward.com", online_resume_url: "www.adriane.ward.com/resume", github_url: "www.github.com/adriane.ward", photo_url: "https://via.placeholder.com/300x300/0259f7/fd28c0.png?text=" },
  { first_name: "Marlen", last_name: "Dooley", email: "marlendooley@example.com", password_digest: "password", phone_number: "844-746-0531", short_bio: "Bicycle rights master cleanse sustainable Williamsburg chambray iPhone before they sold out organic fixie. Messenger bag raw denim 8-bit keytar Four Loko lo-fi DIY. Jean shorts food truck Marfa party VHS. Squid retro freegan Rerry Richardson dreamcatcher.", linkedin_url: "www.linkedin.com/inmarlen.dooley", twitter_handle: nil, personal_website_url: "www.marlen.dooley.com", online_resume_url: "www.marlen.dooley.com/resume", github_url: "www.github.com/marlen.dooley", photo_url: "https://via.placeholder.com/300x300/32b2c4/fa525c.png?text=" },
  { first_name: "Florentina", last_name: "Witting", email: "florentinawitting@example.com", password_digest: "password", phone_number: "752-792-8101", short_bio: "Portland McSweeney's mlkshk Pitchfork brunch fap banh mi. Raw denim art put a bird on it freegan biodiesel McSweeney's yr mixtape seitan. Diy trust fund organic Four Loko Shoreditch vice. Letterpress raw denim fixie Portland butcher cred single-origin coffee Austin freegan.", linkedin_url: "www.linkedin.com/inflorentina.witting", twitter_handle: nil, personal_website_url: "www.florentina.witting.com", online_resume_url: "www.florentina.witting.com/resume", github_url: "www.github.com/florentina.witting", photo_url: "https://via.placeholder.com/300x300/3bb5d7/d9e108.png?text=" },
  { first_name: "Jacinto", last_name: "Kub", email: "jacintokub@example.com", password_digest: "password", phone_number: "826-610-7843", short_bio: "Helvetica stumptown yr jean shorts lomo brunch trust fund skateboard. Hoodie iPhone beard whatever put a bird on it skateboard vegan +1. Shoreditch Rerry Richardson viral yr 8-bit mustache food truck. Mixtape you probably haven't heard of them master cleanse blog vegan tofu vinyl. Food truck jean shorts organic party fap.", linkedin_url: "www.linkedin.com/injacinto.kub", twitter_handle: nil, personal_website_url: "www.jacinto.kub.com", online_resume_url: "www.jacinto.kub.com/resume", github_url: "www.github.com/jacinto.kub", photo_url: "https://via.placeholder.com/300x300/711da8/88676a.png?text=" },
  { first_name: "Tammera", last_name: "Flatley", email: "tammeraflately@example.com", password_digest: "password", phone_number: "807-391-6800", short_bio: "Wes anderson ethical American Apparel fap cliche blog locavore quinoa. Cred iPhone bicycle rights hoodie Shoreditch letterpress. Carles Pitchfork fanny pack tumblr viral. Vinyl next level butcher readymade DIY Rerry Richardson quinoa scenester lomo. Gentrify quinoa jean shorts leggings Pitchfork bicycle rights food truck Brooklyn.", linkedin_url: "www.linkedin.com/intammera.flatley", twitter_handle: nil, personal_website_url: "www.tammera.flatley.com", online_resume_url: "www.tammera.flatley.com/resume", github_url: "www.github.com/tammera.flatley", photo_url: "https://via.placeholder.com/300x300/817743/5669c7.png?text=" },
  { first_name: "Pricilla", last_name: "Streich", email: "pracillastreich@example.com", password_digest: "password", phone_number: "770-452-9534", short_bio: "Put a bird on it retro vinyl 8-bit Wes Anderson keffiyeh. American apparel Williamsburg quinoa Shoreditch food truck yr synth. Cosby sweater fixie Four Loko biodiesel raw denim beard mlkshk yr 8-bit. Master cleanse Austin readymade Cosby Sweater Rerry Richardson party Banksy Carles cliche. Mustache food truck 8-bit skateboard letterpress vinyl tofu art.", linkedin_url: "www.linkedin.com/inpricilla.streich", twitter_handle: nil, personal_website_url: "www.pricilla.streich.com", online_resume_url: "www.pricilla.streich.com/resume", github_url: "www.github.com/pricilla.streich", photo_url: "https://via.placeholder.com/300x300/eb4852/0ec82e.png?text=" },
])

Experience.create!([
  { student_id: 1, start_date: "October 11, 2014", end_date: "Novmber 24, 2020", job_title: "Administrator Officer", company_name: "JetBlue", details: "An Administrative Officer provides day-to-day administrative support to a company or organization. Administrative Officers handle administrative tasks like answering telephone calls, scheduling meetings, preparing reports and filing documents. They may also responsible for managing inventory, maintaining company records, handling budget and office reporting, invoicing and providing customer service. Successful Administrative Officers will also have business management experience and strong industry knowledge to assist with marketing and business development" },
  { student_id: 1, start_date: "January 11, 2010", end_date: "March 24, 2014", job_title: "Anesthesiologist", company_name: "BlackOut", details: "An Anesthesiologist is in charge of maintaining patient comfort before, during and after medical procedures with medication and monitoring the patient’s reaction to those medications. They determine the correct dosage and type of anesthetic to use for a patient and administer the anesthetic drugs during a variety of surgical procedures including cardiac surgery, labor and delivery or dental procedures. Outside of surgery, Anesthesiologists administer drugs to intensive care patients and patients with urgent pain relief needs. " },
  { student_id: 2, start_date: "January 11, 2010", end_date: "January 24, 2014", job_title: "Camp Counselor", company_name: "Camp For You", details: "An Anesthesiologist is in charge of maintaining patient comfort before, during and after medical procedures with medication and monitoring the patient’s reaction to those medications. They determine the correct dosage and type of anesthetic to use for a patient and administer the anesthetic drugs during a variety of surgical procedures including cardiac surgery, labor and delivery or dental procedures. Outside of surgery, Anesthesiologists administer drugs to intensive care patients and patients with urgent pain relief needs." },
  { student_id: 3, start_date: "January 11, 2018", end_date: "March 24, 2014", job_title: "Devops Engineer", company_name: "Operation Complete", details: "A DevOps Engineer is an information technology professional who understands software development and can also solve IT operational challenges by using software engineering tools and processes. A relatively new IT management approach, the DevOps Engineer position requires skills in both software development (Dev) and operations (Ops). A DevOps Engineer must also understand the business needs of their company and have the interpersonal and management skills to get members from these diverse backgrounds to work together." },
  { student_id: 4, start_date: "January 11, 1999", end_date: "January 24, 2011", job_title: "Animator", company_name: "YooHoo", details: "An animator is an artist who creates a series of images known as frames, to simulate movement. Animators draw images by hand or using computer software. Animation may be two-dimensional (2D), three-dimensional (3D), or computer-generated. An animator may work in the entertainment, gaming and advertising industries." },
  { student_id: 5, start_date: "February 11, 2015", end_date: "January 24, 2016", job_title: "Academic Advisor", company_name: "PS104", details: "Academic Advisors work with students in high schools, colleges and universities to help them fulfill requirements for degrees and graduation. Academic advisors also help students select and plan a course of study that will help prepare them for desired career paths. Some academic advisors travel to employment and college fairs to meet potential students and facilitate good relationships with employers and other schools." },
  { student_id: 6, start_date: "June 11, 2015", end_date: "August 24, 2016", job_title: "Busser", company_name: "Bussing", details: "A Busser takes used plates, cups, cutlery and other utensils at restaurants to the kitchen for washing. They also wipe down tables, restock cutlery and paper towels and ensure that tables are ready for the next customer to use. Bussers also assist waitstaff by bringing out food and drink orders and refilling empty water glasses.
  Bussers are important to the running of a restaurant because they keep the dining tables clean and presentable. They also pay close attention to diners and inform the waitstaff when anyone needs something or they attend to it themselves. This excellent service keeps diners coming back." },
  { student_id: 7, start_date: "January 11, 2015", end_date: "March 24, 2016", job_title: "Chef", company_name: "KitchensRus", details: "Chefs work with other kitchen staff to ensure that your kitchen runs effectively, and they have to be experts at ensuring food quality and maintaining kitchen equipment. Other duties and responsibilities that every good Chef has include:
  Ensure that all dishes are cooked well and presented in an aesthetically pleasing way
  Oversee food preparation, checking that all kitchen staff are performing their duties
  Monitor equipment quality and order new equipment as needed
  Help the restaurant determine how much food and supplies need to be ordered
  Train new kitchen staff" },
  { student_id: 7, start_date: "March 11, 2020", end_date: "May 24, 2020", job_title: "Air Traffic controller", company_name: "JFK", details: "Air Traffic Controllers are responsible for the safe, efficient and orderly movement of aircraft. Using computers, radar and visual references, the Air Traffic Controller directs pilots through landings and departures at airports." },
  { student_id: 8, start_date: "November 11, 2020", end_date: "December 24, 2020", job_title: "Dental Hygenist", company_name: "Open Wide", details: "Our growing dental practice needs a Dental Hygienist to join our close-knit team. We serve all demographics of the population, from preschoolers to the elderly, and we operate a busy office with high levels of traffic. In addition to preventive care appointments and scheduled procedures, we accept walk-ins and take emergency calls. If you don't mind working late or on weekends occasionally, you might be a great fit for this position. The ideal candidate will have a calm, reassuring and friendly demeanor as well as the ability to multitask in a fast-paced atmosphere." },
  { student_id: 9, start_date: "November 11, 2020", end_date: "December 24, 2020", job_title: "Dental Hygenist", company_name: "Open Wide", details: "Our growing dental practice needs a Dental Hygienist to join our close-knit team. We serve all demographics of the population, from preschoolers to the elderly, and we operate a busy office with high levels of traffic. In addition to preventive care appointments and scheduled procedures, we accept walk-ins and take emergency calls. If you don't mind working late or on weekends occasionally, you might be a great fit for this position. The ideal candidate will have a calm, reassuring and friendly demeanor as well as the ability to multitask in a fast-paced atmosphere." },
  { student_id: 10, start_date: "November 11, 2020", end_date: "December 24, 2020", job_title: "Dietician", company_name: "Health101", details: "Our organization is in need of a Dietitian to oversee the nutritional well-being of our clients. The successful candidate will have a proven track record of conducting nutrition assessments, identifying patients at risk and creating diet plans. You should be able to analyze the effectiveness of interventions and use metrics to implement data-driven improvements. You should also actively keep up with the latest nutritional research, integrating new findings into diet plans and nutritional services. The ideal applicant has experience providing nutrition education to patients and mitigating risk factors. You must be ready to collaborate with physicians, therapists and nurses in order to tailor dietary services and improve patient outcomes. The Registered Dietitian should be a great communicator, critical thinker and leader." },
  { student_id: 11, start_date: "June 11, 2020", end_date: "current", job_title: "Actuary", company_name: "Actuaries", details: "An Actuary understands how to combine statistics, financial theory, mathematics and business management for the purpose of predicting future events. They work for government agencies, insurance companies, banks, investment firms, hospitals, consulting firms and any business or organization that needs someone to help the operation manage risk. The information brought together by an Actuary is used to determine how much an insurance premium should be or the likelihood certain individuals in an age cohort are going to require a certain kind of medical care and when. The information developed by an Actuary is used by the employer to minimize the company’s exposure to an adverse event." },
])
